# Generated by Django 4.1.5 on 2023-01-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myself',
            name='phone',
        ),
        migrations.AlterField(
            model_name='myself',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
